### ISSUE TITLE
"Styles" is not handled.

### ISSUE THREAD

**Issue by raf555** [PamornT/flex2html#3]
There is a custom "style" for each element (hero, header, body, footer) as seen in this simulator.

![image](https://user-images.githubusercontent.com/8206338/118343749-e5aafa00-b554-11eb-9e76-5dcbeeefe174.png)

And they have their own key.

![image](https://user-images.githubusercontent.com/8206338/118343762-fa878d80-b554-11eb-8a79-a148323923cb.png)

It seems your code is not handling that yet, I tried to add them myself but still not finding any solution, but maybe you can. Thank you so much!

**Comment by PamornT** [comment]
thank for your feedback. i will modify code for support this case.

**Comment by PamornT** [comment]
i already fixed. please pull code again  :)
