### ISSUE TITLE
ที่ไฟล์ flex2html.js  บรรทัด 372

### ISSUE THREAD

**Issue by heart** [PamornT/flex2html#4]
ที่ไฟล์ flex2html.js  บรรทัด 372

  ExBtnfc = 'ExBtnL'

เขียนชื่อตัวแปร ผิดหรือเปล่าครับ

**Comment by PamornT** [comment]
จริงด้วยครับ แก้ไขเรียบร้อยแล้วครับ ขอบคุณมากเลยครับ
