### ISSUE TITLE
box_recursive บั๊ก

### ISSUE THREAD

**Issue by heart** [PamornT/flex2html#6]
box_recursive มัน return parent_box ออกมา
ในกรณีที่ มันควรจุหยุดทำงาน แต่มันส่งตัวเองออกมาเรื่อยๆ 

ทำให้ ในบางครั้ง เช่น มี box ซ้อนกัน 4 level 
แทนที่จะ Recursive ไป 4 ระดับ แล้วจบ
กลับทำให้ วิ่งไปจนสุด Maximum ของ Recursive จน Error

**Comment by PamornT** [comment]
รบกวนส่ง flex json ที่มีปัญหามาให้ทดสอบหน่อยครับ ขอบคุณครับ

**Comment by heart** [comment]
ขอโทษครับ เข้าใจผิดครับ ไม่ใช่ Bug ครับ
