### ISSUE TITLE
bubble img not working

### ISSUE THREAD

**Issue by good1515** [PamornT/flex2html#7]
if bubble 3 img not working

json 

{
  "type": "carousel",
  "contents": [
    {
      "type": "bubble",
      "body": {
        "type": "box",
        "layout": "vertical",
        "contents": [
          {
            "type": "box",
            "layout": "vertical",
            "contents": [
              {
                "type": "image",
                "url": "https://98goto.com/ezs/images/277117130_373628747955338_1203993166101770030_n.jpg",
                "aspectMode": "cover",
                "size": "100%",
                "aspectRatio": "12:6"
              }
            ]
          },
          {
            "type": "box",
            "layout": "vertical",
            "contents": [
              {
                "type": "image",
                "url": "https://98goto.com/ezs/images/277117130_373628747955338_1203993166101770030_n.jpg",
                "size": "100%",
                "aspectMode": "cover",
                "aspectRatio": "12:9"
              }
            ]
          },
          {
            "type": "box",
            "layout": "vertical",
            "contents": [
              {
                "type": "image",
                "url": "https://98goto.com/ezs/images/277117130_373628747955338_1203993166101770030_n.jpg",
                "size": "100%",
                "aspectMode": "cover",
                "aspectRatio": "12:8"
              }
            ]
          }
        ],
        "paddingAll": "0px"
      }
    }
  ]
}

**Comment by PamornT** [comment]
already fixed krab ^^
<img width="315" alt="image" src="https://github.com/PamornT/flex2html/assets/587747/09b8ee79-0829-4f1e-b5a5-6ac1dfed08f9">
